version: '3.8'
services:
db:
image: postgres:15
environment:
POSTGRES_USER: user
POSTGRES_PASSWORD: pass
POSTGRES_DB: tasksdb
volumes:
- pgdata:/var/lib/postgresql/data
ports:
- 5432:5432


app:
build: ./app
environment:
SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasksdb
SPRING_DATASOURCE_USERNAME: user
SPRING_DATASOURCE_PASSWORD: pass
ports:
- 8080:8080
depends_on:
- db


volumes:
pgdata: