name: CI/CD
on:
push:
branches: [ main ]


jobs:
build-and-test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Set up JDK 17
uses: actions/setup-java@v4
with:
java-version: '17'
distribution: 'temurin'
- name: Build and run tests
run: mvn -B clean verify
- name: Run Trivy scan on Dockerfile
uses: aquasecurity/trivy-action@v0.9.3
with:
scan-type: 'fs'
scan-path: './app'


build-and-push-image:
needs: build-and-test
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Log in to registry
uses: docker/login-action@v2
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build and push
uses: docker/build-push-action@v4
with:
context: ./app
push: true
tags: ghcr.io/${{ github.repository_owner }}/devops-project:latest


deploy:
needs: build-and-push-image
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Configure kubectl
uses: azure/setup-kubectl@v3
with:
version: 'latest'
- name: Deploy to Kubernetes
env:
KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
run: |
echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
export KUBECONFIG=$(pwd)/kubeconfig
kubectl apply -f k8s/base